# 파이썬 라이브러리 - numpy

## 1.라이브러리 설치하기

In [2]:
!pip install numpy

In [5]:
import numpy as np

print(np.__version__)
np.__version__

1.23.0


'1.23.0'

## 2.Numpy 사용하기

### 배열 만들기

#### 1차원 배열 만들기

In [1]:
# 리스트와 1차원 배열 만들기
import numpy as np

L = [1,2,3.0,'사과']
arr = np.array([1,2.0,3,4,5,6,7.1,8,9,10])
# arr = np.array(list(range(1,11)))

print(L)
print( type(L) )
print( type(arr) )
print(arr)  # numpy array는 콤마가 없다

[1, 2, 3.0, '사과']
<class 'list'>
<class 'numpy.ndarray'>
[ 1.   2.   3.   4.   5.   6.   7.1  8.   9.  10. ]


#### 2차원 배열 만들기

In [32]:
arr1 = np.array([[10,20,30,40],[50,60,70,80]])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr2*10)

arr1.shape

[[10 20 30 40]
 [50 60 70 80]]
[[10 20 30 40]
 [50 60 70 80]]


(2, 4)

#### 배열의 크기와 차원

In [39]:
print('배열의 크기 :', iris['data'].shape )
print(f"배열의 차원 : {iris['data'].ndim}")

배열의 크기 : (150, 4)
배열의 차원 : 2


### Numpy 사용 예

- 사이킷런 붓꽃 데이터셋

In [38]:
from sklearn.datasets import load_iris 

iris = load_iris()

iris['data']  # = iris.data
iris['data'][0, :]
# iris['data'][0, 1]

배열의 크기 : (150, 4)
배열의 차원 : 2


- OpenCV로 이미지 파일 불러오기

In [ ]:
!pip install opencv-python

In [42]:
import sys
import cv2

print('Hello OpenCV', cv2.__version__)

# image = cv2.imread('image\cat.jpg', cv2.IMREAD_GRAYSCALE)
image = cv2.imread('image\cat.jpg')
if image is None:
    print('Image load failed!')
    sys.exit()

print(image.shape)    
print(image)
print(type(image))
print(image.dtype)    
    
cv2.namedWindow('image')
cv2.imshow("image", image)
cv2.waitKey()
cv2.destroyAllWindows()

Hello OpenCV 4.6.0
(425, 640)
[[234 234 235 ... 238 238 238]
 [234 235 235 ... 238 238 238]
 [235 235 236 ... 238 238 238]
 ...
 [246 246 246 ... 248 248 248]
 [246 246 246 ... 248 248 248]
 [247 247 247 ... 248 248 250]]
<class 'numpy.ndarray'>
uint8


#### 배열의 크기 변경

In [45]:
na = np.arange(12)
print(f'na : {na}')

nb = na.reshape(3, 4)
print(f'nb : {nb}')

nc = na.reshape(2, -1)
print(f'nc : {nc}')

nd = na.reshape(2, -1, 2)
print(f'nd : {nd}')


na : [ 0  1  2  3  4  5  6  7  8  9 10 11]
nb : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
nc : [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
nd : [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
print(type(arr))
# arr : 변수이름
# type() : 데이터형태를 보는 내장함수
# print() : 화면에 출력하는 내장함수

### Numpy 데이터 배열

In [48]:
a1= np.array([1,2,3])
a2= np.array([1,2,3], dtype='float64')
print(a1)
print(a1.dtype)
print(a2)
print(a2.dtype)

[1 2 3]
int32
[1. 2. 3.]
float64


In [52]:
np.finfo('float')

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

### 배열의 연산

In [53]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
z = x + y
z = np.add(x+y)
print(z)

[10002 10004 10006 ... 29996 29998 30000]


In [3]:
x = np.arange(1,21)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
print(f'1번(3의 배수) 답: {x[x%3==0]}')
print(f'2번(4로 나누어 나머지가 1)답: {x[x%4==1]}')
print(f'3번(3의 배수이고 4로 나누어 나머지가 1) 답: {x[(x%3==0)&(x%4==1)]}')

1번(3의 배수) 답: [ 3  6  9 12 15 18]
2번(4로 나누어 나머지가 1)답: [ 1  5  9 13 17]
3번(3의 배수이고 4로 나누어 나머지가 1) 답: [9]
